/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "media_constants.h"

namespace thrift_test {

const mediaConstants g_media_constants;

mediaConstants::mediaConstants() {
}

} // namespace

