/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef media_CONSTANTS_H
#define media_CONSTANTS_H

#include "media_types.h"

namespace thrift_test {

class mediaConstants {
 public:
  mediaConstants();

};

extern const mediaConstants g_media_constants;

} // namespace

#endif
